---
layout: 2017/fall
toc: false
---
:skip-front-matter:

= Conjunto de problemas 1: C

== tl;dr

[start=0]
. Vea la primera ponencia de la semana 1.
. Configure el IDE de CS50 con `hello.c`.
. Recree una de las pirámides de Mario en `mario.c`.
. Acepte algo de efectivo en “cash.c” o de crédito en `credit.c`.
. Envíe el código.
. Envíe un formulario.

include::help-harvard.adoc[]

== Introducción

Recuerde que el IDE de CS50 es un “entorno de desarrollo integrado” basado en Internet que le permite programar “en la nube”, sin instalar ningún software de forma local. Funciona sobre un conocido sistema operativo, Ubuntu Linux, que se ha “implementado en contenedores” con el software de código abierto llamado Docker, que permite que varios usuarios (como usted) compartan el “kernel” (el núcleo, por así decirlo) y los archivos del sistema operativo, aunque cada uno tenga sus propios archivos. De hecho, el IDE de CS50 le proporciona su propia “área de trabajo” (o espacio de almacenamiento), donde puede guardar sus propios archivos y sus carpetas (es decir, los directorios).

=== Inicio de sesión

Acceda a https://cs50.io/[cs50.io] e inicie sesión en el IDE de CS50. Puede que tenga volver a especificar su dirección de correo electrónico. De ser así, después de hacerlo, haga clic en *Private* (Privado) en *Hosted workspace* (Área de trabajo hospedada), seleccione *Harvard's CS50* (CS50 de Hardvard) en *Choose a template* (Seleccione una plantilla) y, a continuación, haga clic en *Create workspace* (Crear área de trabajo).

Se le informará de que el IDE de CS50 (es decir, Cloud9, el software con el que funciona) está “creando el área de trabajo” y “creando el contenedor”, lo que puede tardar un momento. En breve verá su área de trabajo, que será similar a la de David de la semana 1. De no ser así, envíe un correo electrónico a los responsables del curso para solicitar información.

=== Updating

Toward the bottom of CS50 IDE's UI is a "terminal window" (light blue, by default), a command-line interface (CLI) that allows you to explore your workspace's files and directories, compile code, run programs, and even install new software. You should find that its "prompt" resembles the below.

[source]
----
~/workspace/ $
----

Click inside of that terminal window and then type

[source]
----
update50
----

followed by Enter to ensure that your workspace is up-to-date. It might take a few minutes for any updates to complete. (Be sure not to close the tab or CS50 IDE itself until they do!)

Next, execute

[source]
----
mkdir ~/workspace/pset1/
----

at your prompt in order to make a directory called `pset1` in your `workspace` directory. Take care not to overlook the space between `mkdir` and `~/workspace/pset1/` or any other character for that matter! Keep in mind that `~` denotes your home directory, `~/workspace/` denotes a directory called `workspace` therein, and `~/workspace/pset1/` denotes a directory called `pset1` within `~/workspace/`.

Now execute

[source]
----
cd ~/workspace/pset1/
----

to move yourself into (i.e., open) that directory. Your prompt should now resemble the below.

[source]
----
~/workspace/pset1/ $
----

If not, retrace your steps and see if you can determine where you went wrong. You can actually execute

[source]
----
history
----

at the prompt to see your last several commands in chronological order if you'd like to do some sleuthing. You can also scroll through the same one line at a time by hitting your keyboard's up and down arrows; hit Enter to re-execute any command that you'd like.

== What to Do

. Implement link:../../../../problems/hello/hello.html[Hello]
. Implement either of:
+
--
* link:../../../../problems/mario/less/mario.html[Mario], less comfortable
* link:../../../../problems/mario/more/mario.html[Mario], more comfortable
--
+
. Implement either of:
+
--
* link:../../../../problems/cash/cash.html[Cash], less comfortable
* link:../../../../problems/credit/credit.html[Credit], more comfortable
--

== How to Submit

=== Step 1 of 2

. Log into https://cs50.io/[CS50 IDE] and open a terminal window, if not open already.
. Submit Hello by executing:
+
[source]
----
cd ~/workspace/pset1/hello
submit50 cs50/2017/fall/hello
----
. Submit either or both of:
+
--
* Mario, less comfortable, by executing:
+
[source]
----
cd ~/workspace/pset1/mario/less
submit50 cs50/2017/fall/mario/less
----
* Mario, more comfortable, by executing:
+
[source]
----
cd ~/workspace/pset1/mario/more
submit50 cs50/2017/fall/mario/more
----
--
. Submit either or both of:
+
--
* Cash, by executing:
+
[source]
----
cd ~/workspace/pset1/cash
submit50 cs50/2017/fall/cash
----
* Credit, by executing:
+
[source]
----
cd ~/workspace/pset1/credit
submit50 cs50/2017/fall/credit
----
--

=== Step 2 of 2

Submit https://forms.cs50.net/2017/fall/psets/1. Once you have submitted that form (as well as your source code), you are done! If you end up resubmitting your files (per step 1 of 2), no need to resubmit the form.

This was Problem Set 1.
