---
التخطيط: 2017/الخريف
جدول المحتويات: خطأ
---
:skip-front-matter:

= مجموعة المشكلات 1: C

== tl;dr

[start=0]
. مشاهدة أول محاضرة من الأسبوع الأول.
. احصل على إعداد CS50 IDE الخاص بك باستخدام`hello.c`.
. قم بإعادة إنشاء واحد من أهرامات ماريو، في 'mario.c'.
. اقبل بعض النقود في 'cash.c' أو الائتمان في 'credit.c'.
. إرسال الكود الخاص بك.
. إرسال نموذج.

include::help-harvard.adoc[]

=== البدء

تذكر أن CS50 IDE عبارة عن "بيئة تطوير متكاملة" معتمدة على شبكة ويب والتي تسمح لك بالبرمجة "السحابية"، بدون تثبيت أي برامج محلية. تستند هذه البيئة إلى نظام تشغيل شهير، وهو Ubuntu Linux، الذي تم "طرحه" باستخدام برمجيات مفتوحة المصدر تسمى Docker، والتي تسمح لمستخدمين متعددين (مثلك!) بمشاركة "أساس" نظام التشغيل (نواته، إن صح التعبير) وملفاته، حتى إذا كانت هناك ملفات خاصة بهم. يوفر لك CS50 IDE بالفعل "مساحة العمل" الخاصة بك (أي مساحة تخزين) والتي يمكنك حفظ الملفات والمجلدات الخاصة بك فيها (تعرف أيضا باسم الدلائل).

=== جاري تسجيل الدخول

توجه إلى https://cs50.io/[cs50.io] وقم بتسجيل الدخول إلى CS50 IDE. قد تتم مطالبتك (مرة أخرى) بعنوان البريد الإلكتروني الخاص بك. إذا كان الأمر كذلك، فبعد إدخاله، انقر فوق *Private* (خاص) تحت *Hosted workspace* (مساحة العمل المستضافة)، ثم اختر *Harvard's CS50* (دورة جامعة هارفارد CS50) تحت *Choose a template* (اختيار قالب)، وانقر فوق *Create workspace* (إنشاء مساحة عمل).

سيتم إبلاغك بعد ذلك أن CS50 IDE (المعروف بـ Cloud9، البرنامج الذي تعتمد عليه بيئة CS50 IDE) يقوم "بإنشاء مساحة العمل الخاصة بك" و"إنشاء الحاوية الخاصة بك"، وقد يستغرق هذا العمل لحظة. في النهاية، سوف ترى مساحة العمل الخاصة بك، والتي يجب أن تشابه مساحة العمل الخاصة بديفيد الموجودة من الأسبوع الأول. إذا لم يكن الأمر كذلك، فقم فقط بإرسال رسالة بريد إلكتروني إلى رؤساء الدورة للاستفسار!

