---
layout: 2017/fall
toc: false
---
:skip-front-matter:

= مجموعة المشكلات 1: C

== tl;dr

[start=0]
. مشاهدة أول محاضرة من الأسبوع الأول.
. احصل على إعداد CS50 IDE الخاص بك باستخدام `hello.c`.
. قم بإعادة إنشاء واحد من أهرامات ماريو، في `mario.c`.
. اقبل بعض النقود في 'cash.c' أو الائتمان في `credit.c`.
. إرسال الكود الخاص بك.
. إرسال نموذج.

include::help-harvard.adoc[]

=== البدء

	تذكر أن CS50 IDE عبارة عن "بيئة تطوير متكاملة" معتمدة على شبكة ويب والتي تسمح لك بالبرمجة "السحابية" ، بدون تثبيت أي برامج محلية. تستند هذه البيئة إلى نظام تشغيل شهير ، وهو Ubuntu Linux ، الذي تم "طرحه" باستخدام برمجيات مفتوحة المصدر تسمى Docker ، والتي تسمح لمستخدمين متعددين (مثلك!) بمشاركة "أساس" نظام التشغيل (نواته ، إن صح التعبير) وملفاته ، حتى إذا كانت هناك ملفات خاصة بهم. يوفر لك CS50 IDE بالفعل "مساحة العمل" الخاصة بك (أي مساحة تخزين) والتي يمكنك حفظ الملفات والمجلدات الخاصة بك فيها (تعرف أيضا باسم الدلائل).

=== جاري تسجيل الدخول

توجه إلى https:// cs50.io / [cs50.io] وقم بتسجيل الدخول إلى CS50 IDE. قد تتم مطالبتك (مرة أخرى) بعنوان البريد الإلكتروني الخاص بك. إذا كان الأمر كذلك ، فبعد إدخاله ، انقر فوق * Private * (خاص) تحت * Hosted workspace * (مساحة العمل المستضافة) ، ثم اختر * Harvard's CS50 * (دورة جامعة هارفارد CS50) تحت * Choose a template * (اختيار قالب) ، وانقر فوق * Create workspace * (إنشاء مساحة عمل).

سيتم إبلاغك بعد ذلك أن CS50 IDE (المعروف بـ Cloud9 ، البرنامج الذي تعتمد عليه بيئة CS50 IDE) يقوم "بإنشاء مساحة العمل الخاصة بك" و "إنشاء الحاوية الخاصة بك" ، وقد يستغرق هذا العمل لحظة. في النهاية ، سوف ترى مساحة العمل الخاصة بك ، والتي يجب أن تشابه مساحة العمل الخاصة بديفيد الموجودة من الأسبوع الأول. إذا لم يكن الأمر كذلك ، فقم فقط بإرسال رسالة بريد إلكتروني إلى رؤساء الدورة للاستفسار!

=== Updating

Toward the bottom of CS50 IDE's UI is a "terminal window" (light blue, by default), a command-line interface (CLI) that allows you to explore your workspace's files and directories, compile code, run programs, and even install new software. You should find that its "prompt" resembles the below.

[source]
----
~/workspace/ $
----

Click inside of that terminal window and then type

[source]
----
update50
----

followed by Enter to ensure that your workspace is up-to-date. It might take a few minutes for any updates to complete. (Be sure not to close the tab or CS50 IDE itself until they do!)

Next, execute

[source]
----
mkdir ~/workspace/pset1/
----

at your prompt in order to make a directory called `pset1` in your `workspace` directory. Take care not to overlook the space between `mkdir` and `~/workspace/pset1/` or any other character for that matter! Keep in mind that `~` denotes your home directory, `~/workspace/` denotes a directory called `workspace` therein, and `~/workspace/pset1/` denotes a directory called `pset1` within `~/workspace/`.

Now execute

[source]
----
cd ~/workspace/pset1/
----

to move yourself into (i.e., open) that directory. Your prompt should now resemble the below.

[source]
----
~/workspace/pset1/ $
----

If not, retrace your steps and see if you can determine where you went wrong. You can actually execute

[source]
----
history
----

at the prompt to see your last several commands in chronological order if you'd like to do some sleuthing. You can also scroll through the same one line at a time by hitting your keyboard's up and down arrows; hit Enter to re-execute any command that you'd like.

== What to Do

. Implement link:../../../../problems/hello/hello.html[Hello]
. Implement either of:
+
--
* link:../../../../problems/mario/less/mario.html[Mario], less comfortable
* link:../../../../problems/mario/more/mario.html[Mario], more comfortable
--
+
. Implement either of:
+
--
* link:../../../../problems/cash/cash.html[Cash], less comfortable
* link:../../../../problems/credit/credit.html[Credit], more comfortable
--

== How to Submit

=== Step 1 of 2

. Log into https://cs50.io/[CS50 IDE] and open a terminal window, if not open already.
. Submit Hello by executing:
+
[source]
----
cd ~/workspace/pset1/hello
submit50 cs50/2017/fall/hello
----
. Submit either or both of:
+
--
* Mario, less comfortable, by executing:
+
[source]
----
cd ~/workspace/pset1/mario/less
submit50 cs50/2017/fall/mario/less
----
* Mario, more comfortable, by executing:
+
[source]
----
cd ~/workspace/pset1/mario/more
submit50 cs50/2017/fall/mario/more
----
--
. Submit either or both of:
+
--
* Cash, by executing:
+
[source]
----
cd ~/workspace/pset1/cash
submit50 cs50/2017/fall/cash
----
* Credit, by executing:
+
[source]
----
cd ~/workspace/pset1/credit
submit50 cs50/2017/fall/credit
----
--

=== Step 2 of 2

Submit https://forms.cs50.net/2017/fall/psets/1. Once you have submitted that form (as well as your source code), you are done! If you end up resubmitting your files (per step 1 of 2), no need to resubmit the form.

This was Problem Set 1.
